orders/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from . import views


router = routers.SimpleRouter()
router.register(r'pizzas', views.PizzaViewSet)

urlpatterns = [
    url(r'^orders/add/', views.add_order,
        name='add_order'),
    url(r'^orders/list/', views.list_orders,
        name='list_orders'),
    url(r'^orders/edit/(?P<order_id>[0-9])/$', views.editing_order,
        name='edit_order'),
    url(r'^orders/detail/(?P<order_id>[0-9])/$', views.details_order,
        name='details_order'),
    url(r'^orders/action/add_pizza_to_order/(?P<order_id>[0-9])/$', views.add_pizza_to_order,
        name='add_pizza_to_order'),
    url(r'^orders/action/change_status_order/(?P<order_id>[0-9])/$', views.change_status_order,
        name='change_status_order'),
    url(r'^api/v1/', include(router.urls)),
    url(r'^', views.home,
        name='home'),
]

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class BaseModel(models.Model):
    date_created = models.DateTimeField(auto_created=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{class_name} Name: {name}".format(class_name=self.__class__.__name__,
                                                  name=self.__getattribute__('name'))

    class Meta:
        abstract = True


class Pizza(BaseModel):
    name = models.CharField(
        max_length=250
    )
    components = models.ManyToManyField(
        'Component'
    )
    price = models.IntegerField()
    is_active = models.BooleanField(
        default=False
    )
    image = models.ImageField(
        null=True
    )


class Component(BaseModel):
    name = models.CharField(
        max_length=250
    )
    price = models.IntegerField()


class Order(models.Model):
    statuses = (
        ('C', 'Cancelled'),
        ('S', 'Start'),
        ('A', 'Accepted'),
        ('R', 'Realization'),
        ('P', 'Provider'),
        ('E', 'Ended')
    )
    price = models.IntegerField()
    pizzas = models.ManyToManyField(
        Pizza, through='PizzaOrder'
    )
    client = models.ForeignKey(
        User
    )

    date_created = models.DateTimeField(
        auto_created=True,
        auto_now=True
    )
    date_updated = models.DateTimeField(
        auto_now=True
    )

    status = models.CharField(
        max_length=1,
        choices=statuses,
        default='S'
    )

    def __str__(self):
        return "{class_name} Id: {name}".format(class_name=self.__class__.__name__, name=self.id)


class PizzaOrder(models.Model):
    order = models.ForeignKey(
        Order
    )
    pizza = models.ForeignKey(
        Pizza
    )
    count = models.IntegerField(
        default=1
    )

orders/forms.py
from django import forms


class NewOrderForm(forms.Form):
    pizza = forms.IntegerField()


class AddPizzaToOrderForm(forms.Form):
    pizza = forms.IntegerField()


class StatusPizzaForm(forms.Form):
    status = forms.CharField()

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from rest_framework import viewsets

from .forms import NewOrderForm, AddPizzaToOrderForm, StatusPizzaForm
from .models import Pizza, Order, PizzaOrder
from .serializers import PizzaSerializer


def home(request):
    pizzas = Pizza.objects.filter(is_active=True)
    return render(request, 'home.html', {'pizzas': pizzas})


@login_required
def list_orders(request):
    if request.user.is_staff:
        orders = Order.objects.order_by('-date_created')
    else:
        orders = Order.objects.filter(client=request.user).order_by('-date_created')
    return render(request, 'list_orders.html', {'orders': orders})


@login_required
def add_order(request):
    if request.method == 'POST':
        form = NewOrderForm(request.POST)

        if form.is_valid():
            pizza = Pizza.objects.get(pk=form.cleaned_data['pizza'])
            components = pizza.components.all()
            pizza.pk = None
            pizza.is_active = False
            pizza.save()
            pizza.components.add(*components)
            pizza.save()
            order = Order(client=request.user, price=pizza.price)
            order.save()
            order_pizza = PizzaOrder(order=order, pizza=pizza)
            order_pizza.save()
            return redirect('edit_order', order_id=order.id)

    return redirect('home')


@login_required
def details_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'detail_order.html', {'order': order})


@login_required
def editing_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if order.status == 'S' and (request.user.is_staff or order.client == request.user):
        pizzas = Pizza.objects.filter(is_active=True)
        if request.method == 'POST':
            data = request.POST
            for name in data.keys():
                if name != 'csrfmiddlewaretoken':
                    orderpizza = get_object_or_404(PizzaOrder, pk=name)
                    count = int(data[name][0])
                    order.price += (count - orderpizza.count) * orderpizza.pizza.price
                    if count != 0:
                        orderpizza.count = int(data[name][0])
                        orderpizza.save()
                    else:
                        orderpizza.delete()
            order.save()
        return render(request, 'edit_order.html', {'order': order,
                                                   'numbers': range(10),
                                                   'pizzas': pizzas})
    return redirect('details_order', order_id=order.id)


@login_required
def change_status_order(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        form = StatusPizzaForm(request.POST)

        if form.is_valid():
            order.status = form.cleaned_data['status']
            order.save()
    return redirect('details_order', order_id=order.id)


@login_required
def add_pizza_to_order(request, order_id):
    if request.method == 'POST':
        form = AddPizzaToOrderForm(request.POST)

        order = get_object_or_404(Order, pk=order_id)

        if order.status != 'S' and (request.user.is_staff or order.client == request.user):
            return redirect('details_order', order_id=order.id)

        if form.is_valid():
            pizza = get_object_or_404(Pizza, pk=form.cleaned_data['pizza'])
            order_pizza = PizzaOrder(order=order, pizza=pizza)
            order.price += pizza.price
            order.save()
            order_pizza.save()
            return redirect('edit_order', order_id=order.id)

    return redirect('home')


class PizzaViewSet(viewsets.ModelViewSet):
    lookup_field = 'id'
    queryset = Pizza.objects.filter(is_active=True)
    serializer_class = PizzaSerializer

orders/templates/detail_order.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>Pizza name</th>
            <th>Components</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tbody>
        {% for pizza in order.pizzaorder_set.all %}
            <tr>
                <td>{{ pizza.pizza.name }}</td>
                <td>
                    {% for component in pizza.pizza.components.all %}
                        <span class="tag">{{ component.name }}</span>
                    {% endfor %}
                </td>
                <td>
                    {{ pizza.pizza.price|div:100 }}
                </td>
                <td>
                    {{ pizza.count }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table">
    <tr>
        <td>Price</td>
        <td>{{ order.price|div:100 }}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>
            {% if order.status == 'A' %}
                <span class="button is-success">Accepted</span>
            {% elif order.status == 'S' %}
                <span class="button is-info">Started</span>
            {% elif order.status == 'C' %}
                <span class="button is-warning">Cancelled</span>
            {% elif order.status == 'R' %}
                <span class="button is-primary">Realization</span>
            {% elif order.status == 'P' %}
                <span class="button is-primary">Provider</span>
            {% elif order.status == 'E' %}
                <span class="button is-info">Ended</span>
            {% endif %}
        </td>
    </tr>
    {% if user.is_staff %}
    <tr>
        <td>Client</td>
        <td>{{ order.client.first_name }} {{ order.client.last_name }}</td>
    </tr>
    {% endif %}
    </table>
{% endblock %}

orders/templates/edit_order.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table">
            <thead>
            <tr>
                <th>Pizza name</th>
                <th>Components</th>
                <th>Price</th>
                <th>Quantity</th>
            </tr>
            </thead>
            <tbody>
            {% for pizza in order.pizzaorder_set.all %}
                <tr>
                    <td>{{ pizza.pizza.name }}</td>
                    <td>
                        {% for component in pizza.pizza.components.all %}
                            <span class="tag">{{ component.name }}</span>
                        {% endfor %}
                    </td>
                    <td>
                        {{ pizza.pizza.price|div:100 }}
                    </td>
                    <td>
                        <div class="field">
                            <p class="control">
                                <span class="select">
                                      <select name="{{ pizza.id }}" id="{{ pizza.id }}">
                                          {% for number in numbers %}
                                              <option value="{{ number }}" {% if number == pizza.count %}
                                                      selected {% endif %}>{{ number }}</option>
                                          {% endfor %}
                                      </select>
                                </span>
                            </p>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td width="10%"><input class="button is-success" type="submit" value="Accept Change"></td>
            </tr>
            </tfoot>
        </table>
    </form>
    <form action="{% url 'add_pizza_to_order' order_id=order.id %}" method="post">
        {% csrf_token %}
        <table class="table">
            <tbody>
            <tr>
                <td width="90%">
                    <div class="field">
                        <p class="control">
                            <span class="select">
                                <select name="pizza" id="pizza">
                                    {% for pizza in pizzas %}
                                        <option value="{{ pizza.id }}">{{ pizza.name }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </p>
                    </div>
                </td>
                <td><input class="button is-success" type="submit" value="Add pizza to order"></td>
            </tr>
            </tbody>
        </table>
    </form>
    <table class="table">
    <tr>
        <td>Price</td>
        <td>{{ order.price|div:100 }}</td>
    </tr>
        <tr>
            <td>
                <form method="post" action="{% url 'change_status_order' order_id=order.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="A">
                    <input class="button is-success" type="submit" value="Accepted">
                </form>
            </td>
            <td>
                <form method="post" action="{% url 'change_status_order' order_id=order.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="C">
                    <input class="button is-warning" type="submit" value="Cancelled">
                </form>
            </td>
        </tr>
    </table>
{% endblock %}

orders/templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% for pizza in pizzas %}
        {% if forloop.counter0|divisibleby:"3" %}
            <div class="columns">
        {% endif %}
            {% include 'pizza.html' with pizza=pizza %}
        {% if forloop.counter0|add:"-2"|divisibleby:"3" or forloop.last %}
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

orders/templates/list_orders.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Price</th>
            <th>Status</th>
            <th></th>
            {% if user.is_staff %}<th></th>{% endif %}
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.date_created|date:"Y-m-d H:i" }}</td>
                <td>{{ order.price|div:100 }}</td>
                <td>
                    {% if order.status == 'A' %}
                        <span class="button is-success">Accepted</span>
                    {% elif order.status == 'S' %}
                        <span class="button is-info">Started</span>
                    {% elif order.status == 'C' %}
                        <span class="button is-warning">Cancelled</span>
                    {% elif order.status == 'R' %}
                        <span class="button is-primary">Realization</span>
                    {% elif order.status == 'P' %}
                        <span class="button is-primary">Provider</span>
                    {% elif order.status == 'E' %}
                        <span class="button is-info">Ended</span>
                    {% endif %}
                </td>
                <td>
                    {% if order.status == 'S' %}
                        <a href="{% url 'edit_order' order_id=order.id %}" class="button is-success">Edit</a>
                    {% endif %}
                    <a href="{% url 'details_order' order_id=order.id %}" class="button">Details</a>
                </td>
                {% if user.is_staff %}
                    <td>
                        {% if order.status == 'A' %}
                            <form method="post" action="{% url 'change_status_order' order_id=order.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="status" value="R">
                                <input class="button is-success" type="submit" value="Realization">
                            </form>
                        {% elif order.status == 'R' %}
                            <form method="post" action="{% url 'change_status_order' order_id=order.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="status" value="P">
                                <input class="button is-success" type="submit" value="Provided">
                            </form>
                        {% elif order.status == 'P' %}
                            <form method="post" action="{% url 'change_status_order' order_id=order.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="status" value="E">
                                <input class="button is-success" type="submit" value="Ended">
                            </form>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

orders/templates/pizza.html
{% load staticfiles %}
{% load mathfilters %}
<div class="column is-4">
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                {{ pizza.name }}
            </p>
        </header>
        <div class="card-image">
            <figure class="image is-4by3">
                <img src="{{ pizza.image.url }}" alt="Image">
            </figure>
        </div>
        <div class="card-content">
            <div class="panel-block-item">
                <button class="button disabled">{{ pizza.price|div:100 }} zł</button>
                {% for component in pizza.components.all %}
                    <span class="tag">{{ component.name }}</span>
                {% endfor %}
            </div>
        </div>
        <footer class="card-footer">
            <form method="post" action="{% url 'add_order' %}">
                {% csrf_token %}
                <input type="hidden" name="pizza" value="{{ pizza.id }}">
                <input type="submit" class="button is-success " value="Order">
            </form>
        </footer>
    </div>
</div>